/* Static locale pages - a crawlable twin of a page in another language.

   The site's language switcher is client-side: English HTML plus a dictionary
   applied at runtime. Search engines only ever see the English, so nothing
   could rank for a Dutch query. This build takes an English page, applies the
   same dictionary the switcher would, and writes the result as its own URL
   (/nl/websites/), with lang, canonical, og:locale and a full hreflang set, so
   both versions are indexable and point at each other.

   The dictionary stays the single source of truth: translate a string once in
   i18n/<code>.js and both the live switcher and this static page pick it up.
   app.js recognises the generated page by data-i18n-static on <html> and does
   not translate it again; its picker navigates between the hreflang siblings.

   Usage:  node tools/build-locales.js          (writes every page in PAGES)
           node tools/build-locales.js --check  (build in memory, report misses, exit 1 on any) */
'use strict';

var fs = require('fs');
var path = require('path');
var { JSDOM } = require('jsdom');
var { loadDict } = require('./lib/i18n-dict');
var { applyDict } = require('./lib/i18n-apply');

var ROOT = path.join(__dirname, '..');
var SITE = 'https://www.veyago.cloud';

/* Which pages get a static twin, and in which languages. Add a locale here
   once its dictionary covers the page (run with --check to see the gaps). */
var PAGES = [
  { src: 'websites/index.html', path: '/websites/', locales: ['nl', 'de'] }
];

var OG_LOCALE = { en: 'en_US', nl: 'nl_NL', de: 'de_DE', fr: 'fr_FR', es: 'es_ES' };

function localeUrl(pagePath, code) {
  return SITE + (code === 'en' ? '' : '/' + code) + pagePath;
}

function setLink(doc, selector, attrs) {
  var el = doc.querySelector(selector);
  if (!el) { el = doc.createElement('link'); doc.head.appendChild(el); }
  Object.keys(attrs).forEach(function (k) { el.setAttribute(k, attrs[k]); });
  return el;
}

/* The hreflang cluster is identical on every member: each lists all of them,
   itself included, plus x-default pointing at English. */
function hreflangCluster(doc, pagePath, locales) {
  doc.querySelectorAll('link[rel="alternate"][hreflang]').forEach(function (el) { el.remove(); });
  var all = ['en'].concat(locales);
  var canonical = doc.querySelector('link[rel="canonical"]');
  all.forEach(function (code) {
    var el = doc.createElement('link');
    el.setAttribute('rel', 'alternate');
    el.setAttribute('hreflang', code);
    el.setAttribute('href', localeUrl(pagePath, code));
    canonical.parentNode.insertBefore(el, canonical.nextSibling);
  });
  var def = doc.createElement('link');
  def.setAttribute('rel', 'alternate');
  def.setAttribute('hreflang', 'x-default');
  def.setAttribute('href', localeUrl(pagePath, 'en'));
  canonical.parentNode.insertBefore(def, canonical.nextSibling);
}

/* Pure: English HTML in, localised HTML + stats out. */
function buildLocalePage(html, dict, opts) {
  var dom = new JSDOM(html);
  var doc = dom.window.document;
  var url = localeUrl(opts.path, opts.locale);
  var stats = applyDict(doc, dict, opts.path, { pageUrl: localeUrl(opts.path, 'en'), localeUrl: url });
  doc.documentElement.setAttribute('lang', opts.locale);
  doc.documentElement.setAttribute('data-i18n-static', opts.locale);
  setLink(doc, 'link[rel="canonical"]', { rel: 'canonical', href: url });
  var ogUrl = doc.querySelector('meta[property="og:url"]');
  if (ogUrl) ogUrl.setAttribute('content', url);
  var ogLocale = doc.querySelector('meta[property="og:locale"]');
  if (ogLocale) ogLocale.setAttribute('content', OG_LOCALE[opts.locale] || opts.locale);
  hreflangCluster(doc, opts.path, opts.locales);

  var banner = '<!-- Generated by tools/build-locales.js from ' + opts.src + ' + i18n/' + opts.locale + '.js.\n' +
               '     Do not edit: change the English page or the dictionary and run `npm run build:locales`. -->\n';
  var out = dom.serialize().replace(/^<!DOCTYPE html>\s*/i, '<!DOCTYPE html>\n' + banner);
  return { html: out, stats: stats, url: url };
}

function build(opts) {
  opts = opts || {};
  var failures = 0;
  PAGES.forEach(function (page) {
    var html = fs.readFileSync(path.join(ROOT, page.src), 'utf8');
    page.locales.forEach(function (code) {
      var dict = loadDict(code, ROOT);
      var result = buildLocalePage(html, dict, { src: page.src, path: page.path, locale: code, locales: page.locales });
      var missed = result.stats.missed.filter(function (m, i, a) { return a.indexOf(m) === i; });
      var line = '  ' + code + ' ' + page.path + ': ' + result.stats.translated + ' strings, ' +
                 result.stats.attrs + ' attrs, meta ' + (result.stats.meta ? 'yes' : 'NO') +
                 ', ' + missed.length + ' untranslated';
      console.log(line);
      missed.slice(0, opts.verbose ? missed.length : 8).forEach(function (m) { console.log('      - ' + m.slice(0, 90)); });
      if (missed.length > 8 && !opts.verbose) console.log('      ... (' + (missed.length - 8) + ' more; --verbose lists all)');
      if (missed.length) failures++;
      if (!opts.check) {
        var outFile = path.join(ROOT, code, page.path, 'index.html');
        fs.mkdirSync(path.dirname(outFile), { recursive: true });
        fs.writeFileSync(outFile, result.html);
        console.log('    -> ' + path.relative(ROOT, outFile));
      }
    });
  });
  return failures;
}

module.exports = { buildLocalePage, PAGES, localeUrl };

if (require.main === module) {
  var args = process.argv.slice(2);
  var failures = build({ check: args.indexOf('--check') !== -1, verbose: args.indexOf('--verbose') !== -1 });
  if (args.indexOf('--check') !== -1 && failures) process.exit(1);
}
