/* Tests for tools/build-locales.js - the static locale page builder. */
'use strict';

const test = require('node:test');
const assert = require('node:assert');
const { JSDOM } = require('jsdom');
const { buildLocalePage, localeUrl } = require('./build-locales');

const EN = '<!DOCTYPE html>\n<html lang="en"><head><title>Websites | Veyago</title>' +
  '<meta name="description" content="EN desc">' +
  '<link rel="canonical" href="https://www.veyago.cloud/websites/" />' +
  '<link rel="alternate" hreflang="en" href="https://www.veyago.cloud/websites/" />' +
  '<meta property="og:url" content="https://www.veyago.cloud/websites/" />' +
  '<meta property="og:locale" content="en_US" />' +
  '</head><body><h1>Your business, properly online.</h1><p>Untranslated line</p></body></html>';

const DICT = {
  strings: { 'Your business, properly online.': 'Je bedrijf, goed online.' },
  attrs: {}, html: {},
  meta: { '/websites/': { title: 'Websites | Veyago NL', description: 'NL desc' } },
};

const OPTS = { src: 'websites/index.html', path: '/websites/', locale: 'nl', locales: ['nl'] };

test('builds a Dutch twin with its own lang, canonical, og:url and og:locale', () => {
  const { html, stats, url } = buildLocalePage(EN, DICT, OPTS);
  const d = new JSDOM(html).window.document;
  assert.equal(url, 'https://www.veyago.cloud/nl/websites/');
  assert.equal(d.documentElement.getAttribute('lang'), 'nl');
  assert.equal(d.documentElement.getAttribute('data-i18n-static'), 'nl');
  assert.equal(d.querySelector('link[rel="canonical"]').getAttribute('href'), url);
  assert.equal(d.querySelector('meta[property="og:url"]').getAttribute('content'), url);
  assert.equal(d.querySelector('meta[property="og:locale"]').getAttribute('content'), 'nl_NL');
  assert.equal(d.querySelector('h1').textContent, 'Je bedrijf, goed online.');
  assert.equal(d.title, 'Websites | Veyago NL');
  assert.equal(stats.translated, 1);
  assert.deepEqual(stats.missed, ['Untranslated line']);
});

test('the hreflang cluster lists every member plus x-default, replacing whatever the source had', () => {
  const { html } = buildLocalePage(EN, DICT, { ...OPTS, locales: ['nl', 'de'] });
  const d = new JSDOM(html).window.document;
  const links = [...d.querySelectorAll('link[rel="alternate"][hreflang]')].map((l) => [l.getAttribute('hreflang'), l.getAttribute('href')]);
  assert.deepEqual(links.sort(), [
    ['de', 'https://www.veyago.cloud/de/websites/'],
    ['en', 'https://www.veyago.cloud/websites/'],
    ['nl', 'https://www.veyago.cloud/nl/websites/'],
    ['x-default', 'https://www.veyago.cloud/websites/'],
  ]);
});

test('the output announces itself as generated and keeps the doctype first', () => {
  const { html } = buildLocalePage(EN, DICT, OPTS);
  assert.ok(html.startsWith('<!DOCTYPE html>\n<!-- Generated by tools/build-locales.js from websites/index.html + i18n/nl.js.'));
});

test('localeUrl: English lives at the root, everything else under its code', () => {
  assert.equal(localeUrl('/websites/', 'en'), 'https://www.veyago.cloud/websites/');
  assert.equal(localeUrl('/websites/', 'nl'), 'https://www.veyago.cloud/nl/websites/');
});

const { twinPaths, ensureSourceCluster } = require('./build-locales');

test('a twin links to sibling twins, marks its language in the row, and reads euros first', () => {
  const html = '<!DOCTYPE html>\n<html lang="en"><head><title>T</title><meta name="description" content="D">' +
    '<link rel="canonical" href="https://www.veyago.cloud/websites/" /><meta property="og:image" content="https://www.veyago.cloud/assets/og-websites.png" />' +
    '</head><body><nav class="lang-row"><a href="/websites/" hreflang="en" aria-current="page">English</a><a href="/nl/websites/" hreflang="nl">Nederlands</a></nav>' +
    '<a href="/services/#quote">S</a><a href="/privacy/">P</a>' +
    '<div class="tier"><p class="tier-price">$1,690<small>excl. tax</small></p><p class="tier-alt">or €1,790</p></div></body></html>';
  const { html: out } = buildLocalePage(html, { strings: {}, attrs: {}, html: {}, meta: {} },
    { src: 'websites/index.html', path: '/websites/', locale: 'nl', locales: ['nl'], assetExists: (p) => p === '/assets/og-websites-nl.png' });
  const d = new JSDOM(out).window.document;
  assert.equal(d.querySelector('a[href="/nl/services/#quote"]').textContent, 'S', 'a page with a twin links to the twin');
  assert.equal(d.querySelector('a[href="/privacy/"]').textContent, 'P', 'a page without a twin keeps its English link');
  assert.equal(d.querySelector('.lang-row a[hreflang="nl"]').getAttribute('aria-current'), 'page');
  assert.equal(d.querySelector('.lang-row a[hreflang="en"]').getAttribute('aria-current'), null);
  assert.equal(d.querySelector('meta[property="og:image"]').getAttribute('content'), 'https://www.veyago.cloud/assets/og-websites-nl.png');
  assert.equal(d.querySelector('.tier-price').textContent, '€ 1.790excl. tax');
  assert.equal(d.querySelector('.tier-alt').textContent, 'or $ 1.690');
  assert.ok(twinPaths('nl').includes('/services/'));
});

test('the English source gets one hreflang cluster, and rebuilding does not duplicate it', () => {
  const src = '<head>\n  <link rel="canonical" href="https://www.veyago.cloud/services/" />\n  <meta property="og:url" content="x" />\n</head>';
  const once = ensureSourceCluster(src, { path: '/services/', locales: ['nl', 'de'] });
  const twice = ensureSourceCluster(once, { path: '/services/', locales: ['nl', 'de'] });
  assert.equal(once, twice);
  assert.equal((once.match(/hreflang=/g) || []).length, 4);
  assert.ok(once.includes('hreflang="x-default" href="https://www.veyago.cloud/services/"'));
});
