-- =============================================================================
-- notify-task now fires for four events: assigned, updated, done, blocked.
-- email_log.kind is a CHECK constraint (see 0010, 0011, 0014) — three new
-- values are added here.
--
-- Same pattern as 0014: drop whatever constraint currently guards the column
-- (its autogenerated name drifts across Supabase projects), then re-add it
-- with the full list including the new values.
-- =============================================================================

do $$
declare
  c record;
begin
  for c in
    select con.conname
    from   pg_constraint con
    join   pg_class      rel on rel.oid = con.conrelid
    join   pg_namespace  nsp on nsp.oid = rel.relnamespace
    where  con.contype = 'c'
    and    nsp.nspname = 'public'
    and    rel.relname = 'email_log'
    and    con.conname ilike '%kind%'
  loop
    execute format('alter table public.email_log drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.email_log add constraint email_log_kind_check
  check (kind in (
    'invite',
    'password_reset',
    'task_assigned',
    'task_done',
    'task_blocked',
    'task_updated',
    'digest',
    'publish_requested',
    'invoice'
  ));
