-- =============================================================================
-- 0023 — Support tickets: the customer conversation, kept with its context.
--
-- The workspace Tickets view is a queue of customer problems, each with a
-- thread of replies and internal notes. public.tasks is the studio's own work
-- and stays separate: a ticket is something a customer is waiting on, a task
-- is something we decided to do. They link (tickets.project_id) but do not
-- merge.
--
-- Numbering: `number` is an identity column starting at 101, rendered client
-- side as #VYG-142. A sequence rather than a count, so a deleted ticket never
-- makes a later one reuse its number.
--
-- Idempotent. Adds only.
-- =============================================================================

create table if not exists public.support_tickets (
  id          uuid primary key default gen_random_uuid(),
  number      int generated by default as identity (start with 101) unique,
  subject     text not null,
  contact_id  uuid references public.crm_contacts(id) on delete set null,
  company_id  uuid references public.crm_companies(id) on delete set null,
  project_id  uuid references public.client_projects(id) on delete set null,
  product     text,                                  -- 'Kept', 'Veyago travel', a client site
  priority    text not null default 'normal'
                check (priority in ('low','normal','high','urgent')),
  status      text not null default 'open'
                check (status in ('open','in_progress','waiting','resolved','closed')),
  assignee_id uuid references public.employees(id) on delete set null,
  source      text not null default 'manual'
                check (source in ('email','form','manual')),
  first_response_at timestamptz,
  resolved_at timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz
);

create index if not exists support_tickets_queue_idx
  on public.support_tickets (status, priority, created_at desc) where deleted_at is null;
create index if not exists support_tickets_assignee_idx
  on public.support_tickets (assignee_id, status) where deleted_at is null;
create index if not exists support_tickets_contact_idx
  on public.support_tickets (contact_id) where deleted_at is null;

-- ---------------------------------------------------------------------------
-- The thread. `direction` carries the three kinds a support thread actually
-- has: what the customer said, what we sent back, and what we said to each
-- other about it. Internal notes live in the same table so the thread reads in
-- one pass — the front end filters them out of anything customer-facing.
--
-- An author is an employee OR a contact, never both; both null means the
-- system wrote it (a status change, an import).
-- ---------------------------------------------------------------------------
create table if not exists public.ticket_messages (
  id                 uuid primary key default gen_random_uuid(),
  ticket_id          uuid not null references public.support_tickets(id) on delete cascade,
  author_employee_id uuid references public.employees(id) on delete set null,
  author_contact_id  uuid references public.crm_contacts(id) on delete set null,
  direction          text not null default 'outbound'
                       check (direction in ('inbound','outbound','internal')),
  body               text not null,
  created_at         timestamptz not null default now(),
  constraint ticket_messages_single_author
    check (author_employee_id is null or author_contact_id is null)
);

create index if not exists ticket_messages_ticket_idx
  on public.ticket_messages (ticket_id, created_at);

drop trigger if exists support_tickets_touch_updated_at on public.support_tickets;
create trigger support_tickets_touch_updated_at
  before update on public.support_tickets
  for each row execute function public.touch_updated_at();

drop trigger if exists guard_soft_delete on public.support_tickets;
create trigger guard_soft_delete
  before update on public.support_tickets
  for each row execute function public.guard_soft_delete();

-- ---------------------------------------------------------------------------
-- Resolution timestamps, set by the database rather than trusted from the
-- client. Moving a ticket to resolved/closed stamps resolved_at; moving it
-- back out clears it, so "how long was this open" cannot quietly lie.
-- ---------------------------------------------------------------------------
create or replace function public.support_tickets_stamp_resolution()
returns trigger
language plpgsql
as $$
begin
  if new.status in ('resolved','closed') and old.status not in ('resolved','closed') then
    new.resolved_at := now();
  elsif new.status not in ('resolved','closed') and old.status in ('resolved','closed') then
    new.resolved_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists support_tickets_stamp_resolution on public.support_tickets;
create trigger support_tickets_stamp_resolution
  before update of status on public.support_tickets
  for each row execute function public.support_tickets_stamp_resolution();

-- ---------------------------------------------------------------------------
-- A reply bumps its ticket, and the first one out the door sets the response
-- clock. Internal notes deliberately do not count: telling each other about a
-- problem is not answering the customer.
-- ---------------------------------------------------------------------------
create or replace function public.ticket_messages_touch_ticket()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.support_tickets
  set updated_at = now(),
      first_response_at = case
        when new.direction = 'outbound' and first_response_at is null then now()
        else first_response_at
      end
  where id = new.ticket_id;
  return new;
end;
$$;

drop trigger if exists ticket_messages_touch_ticket on public.ticket_messages;
create trigger ticket_messages_touch_ticket
  after insert on public.ticket_messages
  for each row execute function public.ticket_messages_touch_ticket();

-- ---------------------------------------------------------------------------
-- RLS. Private: no anonymous access.
-- ---------------------------------------------------------------------------
alter table public.support_tickets enable row level security;
alter table public.ticket_messages enable row level security;

drop policy if exists "staff read support_tickets" on public.support_tickets;
create policy "staff read support_tickets"
  on public.support_tickets for select using (public.is_staff());

drop policy if exists "staff creates support_tickets" on public.support_tickets;
create policy "staff creates support_tickets"
  on public.support_tickets for insert with check (public.is_staff());

drop policy if exists "staff updates support_tickets" on public.support_tickets;
create policy "staff updates support_tickets"
  on public.support_tickets for update
  using (public.is_staff()) with check (public.is_staff());

drop policy if exists "manager deletes support_tickets" on public.support_tickets;
create policy "manager deletes support_tickets"
  on public.support_tickets for delete using (public.is_manager());

drop policy if exists "staff read ticket_messages" on public.ticket_messages;
create policy "staff read ticket_messages"
  on public.ticket_messages for select using (public.is_staff());

-- Authorship is the caller's own employee row, or nobody's — the same shape as
-- task_comments (0017). You cannot post as a colleague.
drop policy if exists "staff creates ticket_messages" on public.ticket_messages;
create policy "staff creates ticket_messages"
  on public.ticket_messages for insert
  with check (
    public.is_staff()
    and (author_employee_id is null or author_employee_id = public.active_employee_id())
  );

-- A sent reply is a record of what the customer received. Editing it later
-- would make the thread a story rather than a log, so there is no UPDATE
-- policy at all: correct the record by adding another message.
drop policy if exists "manager deletes ticket_messages" on public.ticket_messages;
create policy "manager deletes ticket_messages"
  on public.ticket_messages for delete using (public.is_manager());

comment on table public.support_tickets is
  'Customer problems and their threads. public.tasks is the studio''s own work; '
  'a ticket is something a customer is waiting on.';
comment on table public.ticket_messages is
  'Ticket thread: inbound from the customer, outbound from us, internal notes. '
  'Append-only by design — there is no UPDATE policy.';
